import AuthSideBar from "@/components/AuthSideBar";
import { cn } from "@/lib/utils";
import { Sidebar } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth Page",
  description: "Generated by Muse Feta.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className={cn("min-h-screen w-full bg-white text-black flex", {
            "debug-screens": process.env.NODE_ENV === "development",
          })}
        >
            <AuthSideBar/>
            {children}
        </div>
      </body>
    </html>
  );
}
